### ISSUE TITLE
Mismatch tensor while running demo.py

### ISSUE THREAD

**Issue by dinhtungtp** [NVlabs/prismer#12]
While trying to run demo.py, I see this error
![image](https://user-images.githubusercontent.com/58683392/224606067-19f7728f-1949-4825-bd7a-ebb72f2242ba.png)

hidden_states.shape, and q.shape, k.shape, v.shape as following:
```
hid torch.Size([3, 4, 768])                                                                                                                                                  
torch.Size([3, 12, 4, 64]) torch.Size([3, 12, 4, 64]) torch.Size([3, 12, 4, 64])                                                                                             
hid torch.Size([3, 4, 768])                                                                                                                                                  
torch.Size([3, 12, 4, 64]) torch.Size([9, 12, 900, 64]) torch.Size([9, 12, 900, 64])
```

Do you have any idea what is the problem here? It is an error in `text_decoder.generate()`
I try to run with `prismerz_base`

**Comment by lorenmt** [comment]
Hello, did you change any of the code? It runs no problem from my end.

**Comment by lorenmt** [comment]
Btw, I assume you did not change the config. To run prismerz models, you need to change the config file "experts: 'none'".

**Comment by dinhtungtp** [comment]
It turns out that I was running on a wrong compiler for detectron2 (I used my existing env instead of building a new one). When I build env from scratch, my server show error
`The current installed version of x86_64-linux-gnu-g++ (11.3.0) is greater than the maximum required version by CUDA 11.3 (10.2.1)`

After changing `x86_64-linux-gnu-g++` version and rebuild the env, the code is working now. 

Thank you for your help

**Comment by lorenmt** [comment]
Glad you resolved the problem.

**Comment by lorenmt** [comment]
Resolved with the latest commit. Problem was caused due to transformers package.
