### ISSUE TITLE
I can not understand the generate_config.py

### ISSUE THREAD

**Issue by lanternjx** [NVlabs/prismer#13]
python generate_config.py —-main_ip {MAIN_IP} -—rank {MACHINE_RANK} —-num_machines {TOTAL_MACHINES}

what are the meanings of MAIN_IP MACHINE_RANK TOTAL_MACHINES? And why do we need this step?

python generate_config.py —-main_ip {210.30.97.224} -—rank {0} —-num_machines {1}

I run it as this, but get an erro

**Comment by lorenmt** [comment]
Remove the "{}" just leave the value. But if you just want to work with the demo, then you don't have to do this..

**Comment by lorenmt** [comment]
No further updates.
