### ISSUE TITLE
How to perform inference using VQA

### ISSUE THREAD

**Issue by beyzacevik** [NVlabs/prismer#14]
hello! thank you for your great contribution to the field. 

I would like to know how to perform inference for the VQA part. Could you please add guidance to the readme on 'how to' perform this task? 

thank you

**Comment by lorenmt** [comment]
Hello. VQA inference is pretty much the same as image captioning, except you provide the question as the "prefix". You can check out my inference code for Gradio Prismer Demo: https://huggingface.co/spaces/lorenmt/prismer/blob/d1c3a3a0a2dc02dcf909d6a66a2c8881d5413735/prismer_model.py#L157-L168, to see how I did it.

**Comment by lorenmt** [comment]
No further updates.
