### ISSUE TITLE
Getting error on demo command.

### ISSUE THREAD

**Issue by aaghawaheed** [NVlabs/prismer#15]
![image](https://user-images.githubusercontent.com/16866412/225549565-d890adb6-69a7-47aa-9faf-de9fbceae64b.png)

When I try to execute demo, I am getting error as you can see in the screenshot.

**Comment by lorenmt** [comment]
Could you send me your generated segmentation map? COCO segmentation should have at most 133 class labels.

**Comment by aaghawaheed** [comment]
Actually that error was due to an invalid image file, in the images folder, so script was getting invlid segmentation map on that.

Thanks for the response.
