### ISSUE TITLE
Getting issues on running demo.py as imports have been done wrongly

### ISSUE THREAD

**Issue by chanangad** [NVlabs/prismer#16]
File "/Users/achandhok/Documents/GitHub/prismer/experts/edge/generate_dataset.py", line 10, in <module>
    from dataset.utils import *
ModuleNotFoundError: No module named 'dataset'

dataset folder is not in the current but parent directory

**Comment by lorenmt** [comment]
You should run the demo in the prismer directory. And set `pythonpath=.` Alternatively, I have added the `pythonpath` in the script, so just run `python demo.py --exp_name MODEL_NAME` should work.

**Comment by lorenmt** [comment]
No further updates.
