### ISSUE TITLE
Evaluation on Nocaps fails due to tensor mismatch

### ISSUE THREAD

**Issue by yiyuz** [NVlabs/prismer#18]
When trying to evaluate Prismer_large on Nocaps Val Dataset, I got this error:

> RuntimeError: The size of tensor a (24) must match the size of tensor b (8) at non-singleton dimension 0

The full trace:
https://github.com/yiyuz/prismer_trace/blob/main/trace.txt

I can successfully run the demo.py but fail at train_caption.py (`from_checkpoint` and `evaluate` are set to True).  Do you have any ideas to solve this?

**Comment by lorenmt** [comment]
Could you try to upgrade the 'transformers' package and run it again? I know this is from the beam search..I am quite confused why it works in the demo though?

**Comment by yiyuz** [comment]
Thanks. That fixed the tensor mismatch issue. 

However, another issue arose. When I used `accelerate launch ...`, it hung at 

> captions = model(experts, train=False, prefix=config['prefix'])

I am not sure if the issue is related to accelerate. I have tried `accelerate test` and it worked.

When I didn't use accelerate, I got the error message:

> ValueError: invalid literal for int() with base 10: 'a'

The full trace:
https://github.com/yiyuz/prismer_trace/blob/main/trace.txt

**Comment by lorenmt** [comment]
Hi,

If your command was hung, it is most likely it's waiting for other nodes. But I assume here you are using single-node inference? If so your `accelerator config` did not set up correctly.

Alternatively, you can just launch `accelerator config` and set it up via its text GUI. It's very easy to use. After that don't forget to add flag `--target_dataset nocaps` to inference on NoCaps dataset.

If it still doesn't work, I may need your exact list of commands you use, so I can trace the error.

**Comment by yiyuz** [comment]
Hi,

I am using single-node inference. I launched `accelerate config` as follows:
https://github.com/yiyuz/prismer_trace/blob/main/accelerate_configs.txt 

The command I used is `accelerate launch eval_caption_v0.py --from_checkpoint`. The script I ran has been modified a little bit from `train_caption.py`. I've set the default dataset to nocaps and the exp_name to prismer_large. Plus, when loading the checkpoint, I change the map_location from cpu to cuda:
https://github.com/yiyuz/prismer_trace/blob/main/eval_caption_v0.py

It hung for a long while and generated the following error:

> RuntimeError: Tensors must be CUDA and dense
https://github.com/yiyuz/prismer_trace/blob/main/trace_03290238.txt

**Comment by lorenmt** [comment]
Yea it's the problem when you modify the `train_caption.py`. 
You forgot this line: `model, optimizer, train_loader, test_loader = accelerator.prepare(model, optimizer, train_loader, test_loader)`.

And also, you shouldn't map to `cuda:0` in your multi-gpu inference. Otherwise, your cuda:0 will store the network paramters multiple times, before transferring them to other gpu instances via acceleartor.

**Comment by yiyuz** [comment]
That works. Thank you for checking the code and sorry about the mistake. I've successfully run the script and obtained the captions. In addition, are there evaluation codes available for the CIDEr metric on NoCaps?

**Comment by lorenmt** [comment]
You need to upload it to the eval.ai to get the metric: https://eval.ai/web/challenges/challenge-page/355/overview
