### ISSUE TITLE
Where could I download the answer_list.json for VQA evaluation ?

### ISSUE THREAD

**Issue by doralune** [NVlabs/prismer#19]
It is needed [here](https://github.com/NVlabs/prismer/blob/main/dataset/vqa_dataset.py#L27) when running train_vqa.py --evaluate, but I cannot find it in [dropbox](https://www.dropbox.com/sh/hqtxl1k8gkbhhoi/AACiax5qi7no3pJgO1E57Xefa?dl=0) or https://visualqa.org/download.html.
Or there are the other choices for the evaluation ?

Thank you in advance.

**Comment by lorenmt** [comment]
Sorry. It should be in the dropbox now.

**Comment by doralune** [comment]
Thank you @lorenmt 
but answer_list.json has 3128 items while vqav2_test.json has 447793 items
Is that correct ?

**Comment by lorenmt** [comment]
Yes. You can check the official vqa website for more details. The answer list is organized from BLIP.

**Comment by doralune** [comment]
Thank you @lorenmt 
I got it that the answer was chosen from the list.
