### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Jihyun0510** [NVlabs/prismer#21]
Hi, 
Thanks for sharing your great work!

Only during segmentation label generation when running demo.py, I encounter CUDA out of memory problem.

I tried to allocate it to multiple gpus but won't work out.

I am embarassed to ask such a simple question but could you help me out with this? 

Thank you for your help!

**Comment by lorenmt** [comment]
Hi, It's okay. :) Maybe try to change https://github.com/NVlabs/prismer/blob/3a176bd223c53788886a346910ebec5c34d3de2d/experts/model_bank.py#L43 to Resize(480, 480), so ensure the image has a fixed resolution? Otherwise, you may further decrease the resolution.

Hope that helps.

**Comment by Jihyun0510** [comment]
Thanks for your help!

I changed the codes just as you have mentioned.
![image](https://github.com/NVlabs/prismer/assets/78332579/a417a713-e6a3-47bd-bd7f-b4efa2b76869)

However, this will lead to an error below:
![image](https://github.com/NVlabs/prismer/assets/78332579/77db1c4c-83e0-4cc4-b906-5cd913eadc4c)

What could be done about this??

I really appreciate your help
Thank you

**Comment by lorenmt** [comment]
It's Resize([480, 480]).

**Comment by lorenmt** [comment]
No further updates.
