### ISSUE TITLE
sklearn version

### ISSUE THREAD

**Issue by hikmetli** [NVlabs/prismer#22]
Hi, İ had an issue about cython when i'm trying to install requirements. i think the issue about version of sklearn. It is too old . Here is a part of  the error that i'm getting:

      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
              # Initial capacity
              cdef int init_capacity
      
              if tree.max_depth <= 10:
                  init_capacity = (2 ** (tree.max_depth + 1)) - 1
                                                              ^
      ------------------------------------------------------------
      
      sklearn/tree/_tree.pyx:151:56: Cannot assign type 'double' to 'int'
      Traceback (most recent call last):
        File "/tmp/pip-build-env-ku11v_ed/overlay/local/lib/python3.10/dist-packages/Cython/Build/Dependencies.py", line 1345, in cythonize_one_helper
          return cythonize_one(*m)
        File "/tmp/pip-build-env-ku11v_ed/overlay/local/lib/python3.10/dist-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)

I am getting many errors like this one.Is there any suggestion?

**Comment by lorenmt** [comment]
Hi, sorry I am not sure. It looks like a package version issue, maybe install other versions might be helpful?

**Comment by hikmetli** [comment]
Hi, the error that i got was a cython version as i wrote. Then i realized that the python version is the actual issue. Version of python should be 3.9. I think after 3.10 cython versions are upgraded to 2.And changing it causes different issues. 
I want to ask another question. You are saying that implementation done based on pytorch  1.13 but in requirement torch version is 2. Why?

**Comment by lorenmt** [comment]
The new pytorch 2.0 did not change any APIs and is fully compatible with older versions of pytorch. As it also brings up some additional performance boost with its newly implemented MHA, it's recommended to use pytorch 2.0.
