### ISSUE TITLE
Transformers integration and hosting on HuggingFace?

### ISSUE THREAD

**Issue by altryne** [NVlabs/prismer#3]
Hey, could you guys make this available on hugging face?
Not only due to easier pre-trained weights downloading, but also for being able to add this amazing work to coparisons like this one by @nielsr

https://huggingface.co/spaces/nielsr/comparing-captioning-models

and compare visually.

Thank you for releasing this work open source!

**Comment by lorenmt** [comment]
We are working on that. Stay tuned.

**Comment by lorenmt** [comment]
Solved in the latest commit.

**Comment by altryne** [comment]
@lorenmt thanks for the launch! Is it just me or is it been building for the past 2 hours? 🙏
<img width="360" alt="CleanShot 2023-03-12 at 22 47 48@2x" src="https://user-images.githubusercontent.com/463317/224610557-3bfffdf2-b5a8-43bd-a20f-68bb2e994e96.png">

**Comment by lorenmt** [comment]
Sorry. We were trying further optimize the inference speed. It should be working now.
