### ISSUE TITLE
ruamel.yaml to requirements.txt

### ISSUE THREAD

**Issue by ogencoglu** [NVlabs/prismer#4]
Might be a good idea to add `ruamel.yaml` to the requirements.

**Comment by Starlento** [comment]
I cannot run the script after I `pip install ruamel.yaml` or `pip install ruamel_yaml`, it still reports module not found.
https://stackoverflow.com/questions/49747685/python3-no-module-named-ruamel-yaml
Not really know this package.

**Comment by lorenmt** [comment]
Hi @Starlento, I remember having a similar issue to this. Could you try uninstalling and installing the package again to see whether it works?

**Comment by Starlento** [comment]
> 
Firstly, I cannot search package `ruamel_yaml` here: https://pypi.org/search/?q=ruamel&o=.
And I checked my env:
``` shell
pip list | grep ruamel
ruamel.yaml                   0.17.21
ruamel.yaml.clib              0.2.7
```
And I uninstall both, no matter I `pip install ruamel.yaml`or `pip install ruamel_yaml`, it is installing the same package (I may clear the cache?).
``` shell
Python 3.10.9 (main, Mar  1 2023, 18:23:06) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ruamel_yaml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ruamel_yaml'
>>> import ruamel.yaml
>>> exit()
```

**Comment by lorenmt** [comment]
If you import yaml with `import ruamel.yaml as yaml`, could you successfully run the code? If so I will modify the script a bit to support both versions.

**Comment by Starlento** [comment]
> If you import yaml with `import ruamel.yaml as yaml`, could you successfully run the code? If so I will modify the script a bit to support both versions.

Yes. I can run `demo.py` successfully. And I found that the ruamel.yaml < 0.16 cannot be installed.

**Comment by lorenmt** [comment]
Thanks. Fixed with the new commit.
