### ISSUE TITLE
Add to Replicate.com

### ISSUE THREAD

**Issue by Glavin001** [NVlabs/prismer#5]
Would love to use this on Replicate.com! Thank you!

Related to: https://github.com/NVlabs/prismer/issues/3

**Comment by chenxwh** [comment]
@Glavin001 here is an initial version of it: https://replicate.com/cjwbw/prismer

**Comment by lorenmt** [comment]
Thanks @chenxwh for creating this amazing demo. I will add a label_prettify script to make the labels closer to what I provided in my blog post, to make the visualisation better. I will let you know when it's done.

**Comment by chenxwh** [comment]
Hey @lorenmt! 

Thanks for noticing the demo, I was going to send you a PR so that I can transfer the ownership to your account (if you login with your Github usrname), then you can modify and update the page however you like! Note that Replicate also has API, so the model can be easily used as follows. Let me know! Of course happy to update this when you have the `label_prettify` version too.

```python
import replicate
model = replicate.models.get("cjwbw/prismer")
output = model.predict(image="...")
```

**Comment by lorenmt** [comment]
Really thanks for your kind gesture. I am happy for you to take the ownership, it's your contribution anyways. Give me a couple of hours, let me finish the label prettify script first. 

By the way, I think the segmentation labels predicted by the experts look a bit weird in VQA (all expert labels should be identical independent of the models we use, the caption ones look right), you probably need to look into that.

**Comment by lorenmt** [comment]
@chenxwh, I have offered the prettify script in my latest commit. Please let me know whether that works or not. Again, appreciate your contribution.

**Comment by lorenmt** [comment]
Some other suggestions:
1. I have updated the caption dataset as well, to include `.png` and `.jpeg` files. Otherwise, it will throw an error in the demo.
3. It probably would look cleaner if we put the "model prediction" results at the top of the output column.

Everything else looks perfect!

**Comment by chenxwh** [comment]
perfect, I have updated the demo now here https://replicate.com/cjwbw/prismer, also sending a PR to include the demo link in the README.

Regarding the second point, note that unfortunately the display of the output order of the Replicate demo is random and cannot be easily controlled by [python code](https://github.com/chenxwh/prismer/blob/main/predict.py#L18) now.
