### ISSUE TITLE
Cite a related work

### ISSUE THREAD

**Issue by mrwu-mac** [NVlabs/prismer#6]
An amazing work, and I think it is appropriate to cite our related work [DIFNet: Boosting Visual Information Flow for Image Captioning](https://openaccess.thecvf.com/content/CVPR2022/papers/Wu_DIFNet_Boosting_Visual_Information_Flow_for_Image_Captioning_CVPR_2022_paper.pdf) (CVPR 2022), which has strong relevance to your work.
![image](https://user-images.githubusercontent.com/59433903/223949803-d4057640-8dc8-4bbe-90d7-a4db12f45687.png)

**Comment by lorenmt** [comment]
Hi, thanks for reaching out. There exist too many image captioning papers for which we, unfortunately, are not able to cover everything in our related work section. The paragraph you attached is the proposed future research direction, not the central direction of that paper. And thereby I consider they are not related to each other. Thanks for the understanding.

**Comment by mrwu-mac** [comment]
Thank you for reply. Our DIFNet use extra information flow (Segmentation Flow) to boost image captioning, I think this is related to your work. But I'm sorry if cite it will cause you trouble. Finally, thank you for your outstanding work.
