### ISSUE TITLE
ruamel.yaml import

### ISSUE THREAD

**Issue by bjoernpl** [NVlabs/prismer#7]
The imports of `ruamel.yaml` in the expert files (`experts/generate_*.py`) are still different and should be adapted like in #4 (a9a09d6). That is with:
```python
try:
    import ruamel_yaml as yaml
except ModuleNotFoundError:
    import ruamel.yaml as yaml
```

**Comment by lorenmt** [comment]
Thanks for the notice. Fixed now.
